version: '3.8'
services:
  api_1:
    extends:
      file: docker-compose.yml
      service: api
    environment:
      NODE_ID: atc-api-1
    ports: []

  api_2:
    extends:
      file: docker-compose.yml
      service: api
    environment:
      NODE_ID: atc-api-2
    ports: []

  api_3:
    extends:
      file: docker-compose.yml
      service: api
    environment:
      NODE_ID: atc-api-3
    ports: []

  haproxy:
    image: haproxy:2.8-alpine
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on: [api_1, api_2, api_3]
