export const CORRELATION_LIMITS = {
  MAX_DEPTH: 4,
  MAX_NODES: 200,
  MAX_BREADTH_PER_NODE: 50,
  MAX_LIMIT: 100,
  DEFAULT_LIMIT: 20,
  MAX_TIMELINE_WINDOW_DAYS: 365,
  MAX_ASSOCIATES: 100,
  MAX_CLUSTER_SIZE: 100,
} as const
