CREATE TABLE IF NOT EXISTS atc_vehicle_pursuits (
  id                             VARCHAR(26)  NOT NULL,
  vehicle_runtime_id             VARCHAR(26)  NOT NULL,
  suspect_principal_id           VARCHAR(26)  NOT NULL,
  initiating_officer_principal_id VARCHAR(26) NOT NULL,
  initiating_agency_id           VARCHAR(26)  NULL,
  status                         ENUM('active','ended','escaped','terminated') NOT NULL DEFAULT 'active',
  pursuit_nonce                  VARCHAR(128) NOT NULL,
  start_location_x               FLOAT        NULL,
  start_location_y               FLOAT        NULL,
  start_location_z               FLOAT        NULL,
  end_location_x                 FLOAT        NULL,
  end_location_y                 FLOAT        NULL,
  end_location_z                 FLOAT        NULL,
  started_at                     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ended_at                       DATETIME(3)  NULL,
  notes                          TEXT         NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_pursuit_nonce (pursuit_nonce),
  INDEX idx_pursuit_vehicle_runtime (vehicle_runtime_id),
  INDEX idx_pursuit_suspect (suspect_principal_id),
  INDEX idx_pursuit_status (status),
  INDEX idx_pursuit_started_at (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
