CREATE TABLE IF NOT EXISTS atc_rental_contracts (
  id                   VARCHAR(26)    NOT NULL,
  property_id          VARCHAR(128)   NOT NULL,
  tenant_principal_id  VARCHAR(128)   NOT NULL,
  landlord_principal_id VARCHAR(128)  NOT NULL,
  rent_amount          VARCHAR(24)    NOT NULL DEFAULT '0',
  deposit_amount       VARCHAR(24)    NOT NULL DEFAULT '0',
  rent_cycle_days      INT            NOT NULL DEFAULT 30,
  start_date           DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  end_date             DATETIME(3)    NULL,
  last_payment_at      DATETIME(3)    NULL,
  next_payment_due_at  DATETIME(3)    NOT NULL,
  status               VARCHAR(32)    NOT NULL DEFAULT 'active',
  contract_nonce       VARCHAR(128)   NOT NULL,
  notes                TEXT           NULL,
  created_at           DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at           DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_rental_contract_nonce (contract_nonce),
  INDEX idx_rental_property (property_id),
  INDEX idx_rental_tenant (tenant_principal_id),
  INDEX idx_rental_status (status),
  INDEX idx_rental_next_payment (next_payment_due_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
