CREATE TABLE IF NOT EXISTS atc_npc_runtime (
  id                   VARCHAR(26)    NOT NULL,
  spawn_nonce          VARCHAR(128)   NOT NULL,
  npc_type             VARCHAR(32)    NOT NULL DEFAULT 'civilian',
  model_hash           VARCHAR(128)   NULL,
  owner_server_id      VARCHAR(128)   NULL,
  zone_id              VARCHAR(128)   NULL,
  position_x           FLOAT          NULL,
  position_y           FLOAT          NULL,
  position_z           FLOAT          NULL,
  status               VARCHAR(32)    NOT NULL DEFAULT 'spawned',
  spawned_at           DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  despawned_at         DATETIME(3)    NULL,
  last_heartbeat_at    DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  metadata             JSON           NULL,
  created_at           DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at           DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_npc_spawn_nonce (spawn_nonce),
  INDEX idx_npc_status (status),
  INDEX idx_npc_owner (owner_server_id),
  INDEX idx_npc_zone (zone_id),
  INDEX idx_npc_heartbeat (last_heartbeat_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
