CREATE TABLE IF NOT EXISTS atc_combat_runtime (
  id              VARCHAR(26)   NOT NULL,
  session_id      VARCHAR(128)  NOT NULL,
  entity_id       VARCHAR(128)  NOT NULL,
  target_id       VARCHAR(128)  NULL,
  combat_type     VARCHAR(64)   NOT NULL,
  status          VARCHAR(32)   NOT NULL DEFAULT 'active',
  owner_server_id VARCHAR(128)  NOT NULL,
  region_id       VARCHAR(128)  NULL,
  session_nonce   VARCHAR(128)  NOT NULL,
  combat_data     TEXT          NOT NULL DEFAULT '{}',
  started_at      DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ended_at        DATETIME(3)   NULL,
  created_at      DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at      DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_combat_session_id (session_id),
  UNIQUE KEY uk_combat_session_nonce (session_nonce),
  KEY idx_combat_entity (entity_id),
  KEY idx_combat_status (status),
  KEY idx_combat_server (owner_server_id),
  KEY idx_combat_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
