CREATE TABLE IF NOT EXISTS atc_runtime_failover (
  id                VARCHAR(26)   NOT NULL,
  failover_id       VARCHAR(128)  NOT NULL,
  failover_type     VARCHAR(64)   NOT NULL,
  status            VARCHAR(32)   NOT NULL DEFAULT 'pending',
  source_server_id  VARCHAR(128)  NOT NULL,
  target_server_id  VARCHAR(128)  NOT NULL,
  failover_nonce    VARCHAR(128)  NOT NULL,
  failover_data     TEXT          NOT NULL DEFAULT '{}',
  started_at        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  completed_at      DATETIME(3)   NULL,
  created_at        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_failover_id (failover_id),
  UNIQUE KEY uk_failover_nonce (failover_nonce),
  KEY idx_failover_status (status),
  KEY idx_failover_source (source_server_id),
  KEY idx_failover_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
