CREATE TABLE IF NOT EXISTS atc_runtime_traces (
  id              VARCHAR(26)   NOT NULL,
  trace_id        VARCHAR(128)  NOT NULL,
  trace_type      VARCHAR(64)   NOT NULL,
  status          VARCHAR(32)   NOT NULL DEFAULT 'active',
  source_node     VARCHAR(128)  NOT NULL,
  target_node     VARCHAR(128)  NULL,
  owner_server_id VARCHAR(128)  NOT NULL,
  trace_nonce     VARCHAR(128)  NOT NULL,
  trace_data      TEXT          NOT NULL DEFAULT '{}',
  started_at      DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  completed_at    DATETIME(3)   NULL,
  created_at      DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at      DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_trace_nonce (trace_nonce),
  KEY idx_trace_status (status),
  KEY idx_trace_owner (owner_server_id),
  KEY idx_trace_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
