CREATE TABLE IF NOT EXISTS atc_runtime_threats (
  id              VARCHAR(26)  NOT NULL,
  threat_id       VARCHAR(26)  NOT NULL,
  threat_type     ENUM('botnet','exploit','dos','data_leak','privilege_escalation','custom') NOT NULL,
  severity        ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  status          ENUM('active','mitigated','resolved','escalated') NOT NULL DEFAULT 'active',
  owner_server_id VARCHAR(128) NOT NULL,
  entity_id       VARCHAR(128) NULL,
  threat_nonce    VARCHAR(128) NOT NULL,
  resolved_at     DATETIME(3)  NULL,
  threat_data     JSON         NOT NULL,
  created_at      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_runtime_threat_id (threat_id),
  UNIQUE KEY uq_runtime_threat_nonce (threat_nonce, owner_server_id),
  KEY idx_runtime_threats_status (status),
  KEY idx_runtime_threats_severity (severity),
  KEY idx_runtime_threats_entity (entity_id),
  KEY idx_runtime_threats_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
