export { AtcHealthService } from './health.js'
export type {
  AtcHealthServiceOptions,
  DbCheckable,
  RedisCheckable,
  EventBusCheckable,
  TaskRuntimeCheckable,
  EventStoreCheckable,
  PluginRuntimeCheckable,
} from './health.js'

export {
  subsystemHealthSchema,
  healthSnapshotSchema,
  diagnosticsQuerySchema,
  dlqQuerySchema,
  requeueTaskSchema,
  opsEventQuerySchema,
  runtimeNodeStatusSchema,
  clusterSnapshotSchema,
  pluginRuntimeStatusSchema,
  pluginResourceUsageSchema,
  pluginHealthSnapshotSchema,
  pluginLifecycleActionSchema,
  principalTypeSchema,
  authorizeRequestSchema,
  capabilityCheckRequestSchema,
  auditQuerySchema,
  listPrincipalsQuerySchema,
  createPrincipalSchema,
  updatePrincipalSchema,
  assignRoleSchema,
  grantCapabilitySchema,
} from './schemas.js'
export type {
  DlqQuery,
  RequeueTask,
  OpsEventQuery,
  ClusterSnapshot,
  PluginRuntimeStatus,
  PluginResourceUsage,
  PluginHealthSnapshot,
  PluginLifecycleAction,
  AuthorizeRequest,
  CapabilityCheckRequest,
  AuditQuery,
  ListPrincipalsQuery,
  CreatePrincipalRequest,
  UpdatePrincipalRequest,
  AssignRoleRequest,
  GrantCapabilityRequest,
  CreateFinancialAccountRequest,
  UpdateFinancialAccountRequest,
  TransferRequest,
  CommitJournalRequest,
  ReverseJournalRequest,
  CreateOrganizationRequest,
  AddMemberRequest,
  IssueInvoiceRequest,
  PayInvoiceRequest,
  ListJournalsQuery,
  ListAccountsQuery,
  ListInvoicesQuery,
} from './schemas.js'
export {
  createFinancialAccountSchema,
  updateFinancialAccountSchema,
  transferSchema,
  commitJournalSchema,
  reverseJournalSchema,
  createOrganizationSchema,
  addMemberSchema,
  issueInvoiceSchema,
  payInvoiceSchema,
  listJournalsQuerySchema,
  listAccountsQuerySchema,
  listInvoicesQuerySchema,
  createShopSchema,
  updateShopStatusSchema,
  upsertShopItemSchema,
  purchaseSchema,
  sellSchema,
  listOrdersQuerySchema,
  listReceiptsQuerySchema,
  createTaxRuleSchema,
  listShopsQuerySchema,
} from './schemas.js'
export type {
  CreateShopRequest,
  UpdateShopStatusRequest,
  UpsertShopItemRequest,
  PurchaseRequest,
  SellRequest,
  ListOrdersQuery,
  ListReceiptsQuery,
  CreateTaxRuleRequest,
  ListShopsQuery,
} from './schemas.js'
export {
  createJobSchema,
  updateJobSchema,
  createJobGradeSchema,
  listJobsQuerySchema,
  createContractSchema,
  terminateContractSchema,
  listContractsQuerySchema,
  clockInSchema,
  clockOutSchema,
  listWorkSessionsQuerySchema,
  previewPayrollSchema,
  commitPayrollSchema,
} from './schemas.js'
export type {
  CreateJobRequest,
  UpdateJobRequest,
  CreateJobGradeRequest,
  ListJobsQuery,
  CreateContractRequest,
  TerminateContractRequest,
  ListContractsQuery,
  ClockInRequest,
  ClockOutRequest,
  ListWorkSessionsQuery,
  PreviewPayrollRequest,
  CommitPayrollRequest,
} from './schemas.js'
export {
  createAgencySchema,
  listAgenciesQuerySchema,
  issueWarrantSchema,
  revokeWarrantSchema,
  listWarrantsQuerySchema,
  issueCitationSchema,
  payCitationSchema,
  listCitationsQuerySchema,
  recordArrestSchema,
  listArrestsQuerySchema,
  enterJailSchema,
  releaseJailSchema,
  collectEvidenceSchema,
  transferCustodySchema,
  listEvidenceQuerySchema,
  createLegalCaseSchema,
  listLegalCasesQuerySchema,
} from './schemas.js'
export type {
  CreateAgencyRequest,
  ListAgenciesQuery,
  IssueWarrantRequest,
  RevokeWarrantRequest,
  ListWarrantsQuery,
  IssueCitationRequest,
  PayCitationRequest,
  ListCitationsQuery,
  RecordArrestRequest,
  ListArrestsQuery,
  EnterJailRequest,
  ReleaseJailRequest,
  CollectEvidenceRequest,
  TransferCustodyRequest,
  ListEvidenceQuery,
  CreateLegalCaseRequest,
  ListLegalCasesQuery,
} from './schemas.js'

export {
  createDispatchCallSchema,
  listDispatchCallsQuerySchema,
  acceptDispatchCallSchema,
  createIncidentSchema,
  listIncidentsQuerySchema,
  addIncidentNoteSchema,
  assignResponderSchema,
  updateResponderStatusSchema,
  createBoloSchema,
  listBolosQuerySchema,
  addBoloNoteSchema,
} from './schemas.js'
export type {
  CreateDispatchCallRequest,
  ListDispatchCallsQuery,
  AcceptDispatchCallRequest,
  CreateIncidentRequest,
  ListIncidentsQuery,
  AddIncidentNoteRequest,
  AssignResponderRequest,
  UpdateResponderStatusRequest,
  CreateBoloRequest,
  ListBolosQuery,
  AddBoloNoteRequest,
} from './schemas.js'

export {
  recordInjurySchema,
  listInjuriesQuerySchema,
  updateTraumaSchema,
  revivePatientSchema,
  applyTreatmentSchema,
  createMedicalReportSchema,
  closeMedicalReportSchema,
  listMedicalReportsQuerySchema,
  admitToHospitalSchema,
  updateHospitalStatusSchema,
} from './schemas.js'
export type {
  RecordInjuryRequest,
  ListInjuriesQuery,
  UpdateTraumaRequest,
  RevivePatientRequest,
  ApplyTreatmentRequest,
  CreateMedicalReportRequest,
  CloseMedicalReportRequest,
  ListMedicalReportsQuery,
  AdmitToHospitalRequest,
  UpdateHospitalStatusRequest,
} from './schemas.js'

export {
  createEmergencySchema,
  triageEmergencySchema,
  assignEmergencySchema,
  stabilizeEmergencySchema,
  transportEmergencySchema,
  closeEmergencySchema,
} from './schemas.js'
export type {
  CreateEmergencyRequest,
  TriageEmergencyRequest,
  AssignEmergencyRequest,
  StabilizeEmergencyRequest,
  TransportEmergencyRequest,
  CloseEmergencyRequest,
} from './schemas.js'
export {
  registerVehicleSchema,
  spawnVehicleSchema,
  retrieveVehicleSchema,
  storeVehicleSchema,
  impoundVehicleSchema,
  releaseVehicleSchema,
  syncRuntimeSchema,
  assignFleetSchema,
  unassignFleetSchema,
  vehicleListQuerySchema,
} from './schemas.js'
export type {
  RegisterVehicleRequest,
  SpawnVehicleRequest,
  RetrieveVehicleRequest,
  StoreVehicleRequest,
  ImpoundVehicleRequest,
  ReleaseVehicleRequest,
  SyncRuntimeRequest,
  AssignFleetRequest,
  UnassignFleetRequest,
} from './schemas.js'
export {
  registerPropertySchema,
  purchasePropertySchema,
  enterPropertySchema,
  exitPropertySchema,
  lockPropertySchema,
  unlockPropertySchema,
  breachPropertySchema,
  endBreachSchema,
  seizePropertySchema,
  grantAccessSchema,
  revokeAccessSchema,
  issueKeySchema,
  depositStorageSchema,
  withdrawStorageSchema,
  linkGarageSchema,
  retrieveFromPropertySchema,
} from './schemas.js'
export type {
  RegisterPropertyRequest,
  PurchasePropertyRequest,
  EnterPropertyRequest,
  ExitPropertyRequest,
  LockPropertyRequest,
  UnlockPropertyRequest,
  BreachPropertyRequest,
  EndBreachRequest,
  SeizePropertyRequest,
  GrantAccessRequest,
  RevokeAccessRequest,
  IssueKeyRequest,
  DepositStorageRequest,
  WithdrawStorageRequest,
  LinkGarageRequest,
  RetrieveFromPropertyRequest,
} from './schemas.js'
export {
  registerWeaponSchema,
  equipWeaponSchema,
  unequipWeaponSchema,
  syncAmmoSchema,
  applyDamageSchema,
  startCombatSessionSchema,
  endCombatSessionSchema,
  applyInjurySchema,
  seizeWeaponSchema,
} from './schemas.js'
export type {
  RegisterWeaponRequest,
  EquipWeaponRequest,
  UnequipWeaponRequest,
  SyncAmmoRequest,
  ApplyDamageRequest,
  StartCombatSessionRequest,
  EndCombatSessionRequest,
  ApplyInjuryRequest,
  SeizeWeaponRequest,
} from './schemas.js'
export {
  createGangSchema,
  addGangMemberSchema,
  createOperationSchema,
  operationOutcomeSchema,
  registerContrabandSchema,
  seizeContrabandSchema,
  recordTradeSchema,
  stageRaidSchema,
  completeRaidSchema,
  abortRaidSchema,
} from './schemas.js'
export type {
  CreateGangRequest,
  AddGangMemberRequest,
  CreateOperationRequest,
  OperationOutcomeRequest,
  RegisterContrabandRequest,
  SeizeContrabandRequest,
  RecordTradeRequest,
  StageRaidRequest,
  CompleteRaidRequest,
  AbortRaidRequest,
} from './schemas.js'
export {
  registerEntitySchema,
  reconcileEntitySchema,
  createSceneSchema,
  persistSceneSchema,
  scheduleCleanupSchema,
} from './schemas.js'
export type {
  RegisterEntityRequest,
  ReconcileEntityRequest,
  CreateSceneRequest,
  PersistSceneRequest,
  ScheduleCleanupRequest,
} from './schemas.js'

// ── Phase 35: Vehicle Simulation ─────────────────────────────────────────────
export {
  syncFuelSchema,
  consumeFuelSchema,
  refuelSchema,
  syncDamageSchema,
  applyVehicleDamageSchema,
  registerVehicleRegistrationSchema,
  startPursuitSchema,
  endPursuitSchema,
  recordViolationSchema,
  vehicleHeartbeatSchema,
} from './schemas.js'
export type {
  SyncFuelRequest,
  ConsumeFuelRequest,
  RefuelRequest,
  SyncDamageRequest,
  ApplyVehicleDamageRequest,
  RegisterVehicleRegistrationRequest,
  StartPursuitRequest,
  EndPursuitRequest,
  RecordViolationRequest,
  VehicleHeartbeatRequest,
} from './schemas.js'

// ── Phase 36: Banking & Market Runtime ───────────────────────────────────────
export {
  bankTransferSchema,
  freezeAccountSchema,
  createListingSchema,
  purchaseListingSchema,
  createAuctionSchema,
  placeBidSchema,
  settleAuctionSchema,
} from './schemas.js'
export type {
  BankTransferRequest,
  FreezeAccountRequest,
  CreateListingRequest,
  PurchaseListingRequest,
  CreateAuctionRequest,
  PlaceBidRequest,
  SettleAuctionRequest,
} from './schemas.js'

// ── Phase 37: Faction & Territory Runtime ────────────────────────────────────
export {
  createFactionSchema,
  claimTerritorySchema,
  startConflictSchema,
  resolveConflictSchema,
  captureResourceNodeSchema,
  addFactionMemberSchema,
} from './schemas.js'
export type {
  CreateFactionRequest,
  ClaimTerritoryRequest,
  StartConflictRequest,
  ResolveConflictRequest,
  CaptureResourceNodeRequest,
  AddFactionMemberRequest,
} from './schemas.js'
